### ISSUE TITLE
TypeError: connect.server is not a function

### ISSUE THREAD

**Issue by mehdiraized** [micahblu/gulp-connect-php#54]
how to fix error TypeError: connect.server is not a function ?

**Comment by grmartin** [comment]
Can you give me more context? The gulp file, version of gulp, Node, the module?

**Comment by mv-ngwenya** [comment]
Having the same problem

node version 8.9.4
gulp version 3.9.1
gulp-connect-php 1.0.2

gulpfile
```
var gulp = require('gulp'),
    connect = require('gulp-connect-php');

gulp.task('connect', function() {
    connect.server();
});

gulp.task('default', ['connect']);
```

**Comment by lobo87** [comment]
Same problem here

node version 9.7.0
gulp version 3.9.1
gulp-connect-php 1.0.2

i was working with the plugin for at least 6 months now without problems. I had to reinstall the node packages today and since then `require` returns an empty object for `connect`. Copying the old node_modules folder fixes the issue. 

I was using gulp-connect-php in version 1.0.1 before. However reverting does not solve the issue. 

Maybe it's related to a dependency? Here are the devDeps im using

```
"devDependencies": {
    "browser-sync": "^2.18.8",
    "del": "^3.0.0",
    "eslint": "^4.6.1",
    "eslint-config-airbnb-base": "^12.0.0",
    "eslint-plugin-import": "^2.7.0",
    "gulp": "^3.9.1",
    "gulp-connect-php": "^1.0.1",
    "gulp-if": "^2.0.2",
    "gulp-imagemin": "^3.3.0",
    "gulp-load-plugins": "^1.5.0",
    "gulp-sass": "^3.1.0",
    "gulp-uglify": "^3.0.0",
    "gulp-useref": "^3.1.2",
    "run-sequence": "^1.2.2",
    "sass-lint": "^1.11.1"
  }
```

**Comment by grmartin** [comment]
So this is actually caused by #55... I am resolving that now and will have a 1.0.3 prepped shortly.

**Comment by grmartin** [comment]
1.0.3 just went out. @mehdiraized, @mv-ngwenya, @lobo87 mind testing?

**Comment by RyanDeegan** [comment]
@grmartin had the same issue this afternoon. Just tested with 1.0.3 and it works. Thanks.

**Comment by grmartin** [comment]
@mehdiraized once you confirm, ill close this.

**Comment by lobo87** [comment]
I just tested 1.0.3 and it works. Thanks!

**Comment by hrkfdn** [comment]
1.0.3 fixed it for me, as well! Thanks!

**Comment by grmartin** [comment]
I’ll take this as a consensus, if OP is still having issues feel free to reopen this issue.

**Comment by mehdiraized** [comment]
I just tested 1.0.3 and it works. Thanks! ❤️🙏🏻☺️
